### ISSUE TITLE
Brand Logo in Email

### ISSUE THREAD

**Issue by schorsch8878** [itx-informationssysteme/jobapplications#58]
The emails vor application and notification uses the login logo from backend ext. We use one typo3 for 2 different sites from the same owner. Is there a possibility to change the logo and the color in the mail? In the mailtemplate i found nothing

many thank

**Comment by itx-stefanie-doell** [comment]
The email templates use the TYPO3 standard mail layout: <f:layout name="SystemEmail"/>, which refers to the template typo3/sysext/core/Resurces/Private/Layouts/SystemEmail.html. You could try to overwrite this core layout template, since it is used in a lot of extensions, where you will probably have the same problem. Your second option is that you can overwrite the Jobapplications mail templates with custom templates according to your needs.

**Comment by schorsch8878** [comment]
Many Thanks!
