### ISSUE TITLE
Make Opengraph Data editable

### ISSUE THREAD

**Issue by akroii** [itx-informationssysteme/jobapplications#84]
Hi,
it would be nice to have full access for open graph data, not just automatic generation. Sometime we have to shift different title and desciprtion.
If the Backend Fields leave empty then the output can be generate automatically.

**Comment by itx-stefanie-doell** [comment]
Hi,
thank you for your feedback. 
In older versions we had open graph data in a template, but we had the impression that this was very confusing.
So we changed the implementation to a json file in the header data. Everything happens in the function "addGoogleJobsDataToPage" in the PostingController.php - this is an encapsulation by design so it can be easily overwritten.
I have problems  imagining how this can be made editable, because there are a lot of exceptions to make everything the way google likes it, for example the salary implementation:
`			if (!empty($posting->getBaseSalary()))
			{
				$currency = $logo = $extconf->get('jobapplications', 'currency') ?: "EUR";
				$googleJobsJSON["baseSalary"] = [
					"@type" => "MonetaryAmount",
					"currency" => $currency,
					"value" => [
						"@type" => "QuantitativeValue",
						"value" => preg_replace('/\D/', '', $posting->getBaseSalary()),
						"unitText" => "YEAR"
					]
				];
			}`

Maybe a yaml file which provides the right mapping? I have the feeling that yaml file configurations are usually so complicated that they aren't any easier than overwriting a function. Or maybe a hook would be a good idea, so someone could modify the googleJobsJson before it is added to the header?
Can you please describe which kind of access you had in mind? If you want to, you can also describe your use case in detail, maybe we can figure out some other solution for you (e.g. additional opengraph fields or something like that...)

**Comment by akroii** [comment]
Hi Stefanie,
it would be sufficient if only these fields were present:

```
og:description
og:title
og:image
og:image:url
og:image:width
og:image:height
og:type
og:site_name
twitter:card
twitter:image
```

Simply all fields were which jobapplications is filled automatically.
To have full control over the fields it would be necessary to be able to edit these fields as well:

```
og:site_name
og:url
og:image:type
og:image:width
og:image:height
twitter:creator
twitter:title
twitter:url
twitter:description
twitter:image:width
twitter:image:height
twitter:image:alt
```

**Comment by itx-stefanie-doell** [comment]
ah, thanks a lot for clarification - I thought you're referencing the open graph information for google for jobs.
For the described tags you can overwrite the Partial Posting/MetaTags and customize it to your needs. Of course you can add new types there as well.
I hope this helps!

**Comment by akroii** [comment]
#Of course you can add new types there as well.
Can you give me a small hint, how to do that? Can this done via TCA?
